### ISSUE TITLE
Azure/azure-content-frfr/README.md: Repository organization section is about the English repo

### ISSUE THREAD

**Issue by brunolewin** [Azure/azure-content-frfr#3]
The Repository organization section ("Organisation du dépôt") outlines the structure of the English repo, which contains more things than the translated one - would be good to outline the differences and callout that someone editing a French article can/should go to the English repo for things like templates, etc.

**Comment by SunnyDeng** [comment]
@brunolewin, thank you for the feedback. the article structure between frfr and enus are the same when the files apply to the frfr situation.
