### ISSUE TITLE
Inconsistencies in French translation of "streaming" (incl. in Term Studio)

### ISSUE THREAD

**Issue by brunolewin** [Azure/azure-content-frfr#5]
I noticed a inconsistency around how "streaming", "On demand streaming" and "Live Streaming" are translated in the French. Looking further, the inconsistency also appears in TermStudio:
- Options for **live** streaming include: "vidéo en flux continu", "streaming en direct", etc 
- "streaming" is translated in TermStudio as "diffusion en continu" (meaning "live broadcast")

Having a different French term for "streaming" across Azure topics makes for a harder read and harder search. Since "streaming" seems acceptable in some context, maybe this could become the way we refer to all types of streaming.

**Comment by SunnyDeng** [comment]
@brunolewin, thank you for the feedback. @v-fedi for fixing.
