### ISSUE TITLE
FR: Consider using English terms for Pull Request and other Github actions in the Community Contribution process

### ISSUE THREAD

**Issue by brunolewin** [Azure/azure-content-frfr#6]
The current term in Term Studio for "Pull Request" is "requête de tirage" and translators seem to use that diligently. This feels odd, especially given that:
- we are using English GitHub to edit the French docs
- many French speakers use "Pull Request" to refer to a Pull Request
- I have not seem much use of "requête de tirage"

Could we consider using English terms for Github actions in the Community Contribution process

**Comment by SunnyDeng** [comment]
Thank you for the feedback! @karinanderke
